#!/usr/bin/python

import smbus
import math
import os
from gps import *
from time import *
import threading
import serial
import smbus
import time
import datetime
from datetime import date


#Settings 
sleeptime=1
alt_divider=10  #every x loops, take a new alt measurment 


#Create text files
f=open('rocketlog.txt', 'a')
brakes=open('brakes_control.txt','a')


#Open serial port 
altimeter = serial.Serial(
              
               port='/dev/ttyAMA0',
               baudrate = 9600,
               parity=serial.PARITY_NONE,
               stopbits=serial.STOPBITS_ONE,
               bytesize=serial.EIGHTBITS,
               timeout=10
           )


#Define Initial Variables 
Alt_proj=0
Alt_current=0
Second_Alt = 0
count=0
while True:
  
    starttime = time.time()
    Alt_current =int(altimeter.readline())
    V_current = (abs(Alt_current - Second_Alt))/(abs(starttime-endtime))
    
    
    
    
    
    
    
    
    
    
    now = datetime.datetime.now()
    timestamp = now.strftime("%H:%M:%S")
    writestring = str(timestamp)+","+str(Second_Alt)+","+str(V_current)+"\n"
    f.write(writestring)
    
    
    sleep(sleeptime) 
    
    
    endtime = time.time()
    Second_Alt=int(altimeter.readline())
    
   


   
